path:
  ckpt_path: "./output/ckpt/"
  log_path: "./output/log/"
  result_path: "./output/result/"
  exp_name: "kokoro_2"
  train_path: train.txt
  val_path: val.txt
  restore_path: ""
optimizer:
  batch_size: 64
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  lr: 0.001
step:
  total_step: 15000
  warm_up_step: 1500
  synth_step: 300
  save_step: 1500
trainer:
  grad_clip_thresh: 1.0
  grad_acc: 1